/**
 * DACS Dashboards — data source layer
 * ------------------------------------
 * Single place where dashboards get their data.
 *
 * MODE 1 (current): static JSON snapshot committed to the repo
 *                   (data/orders.json — can be regenerated by an export
 *                   job on the DACS test platform).
 *
 * MODE 2 (later):   live API. Point API_BASE to an Azure Function /
 *                   Static Web Apps "api/" proxy that calls the DACS
 *                   test platform server-side (credentials stay there,
 *                   no CORS issue since same domain).
 *                   Example:  const API_BASE = '/api';
 *                   Expected endpoint: GET {API_BASE}/orders  → same
 *                   JSON shape as data/orders.json.
 */

const API_BASE = null; // e.g. '/api' once the Azure Function proxy exists

// Embedded fallback so the page also works when opened as a local file
// (fetch() is blocked on file:// by browsers).
const EMBEDDED_FALLBACK_URL = 'data/orders.json';

let _cache = null;

async function loadDataset() {
  if (_cache) return _cache;
  const url = API_BASE ? `${API_BASE}/orders` : EMBEDDED_FALLBACK_URL;
  const res = await fetch(url, { cache: 'no-store' });
  if (!res.ok) throw new Error(`Data source unavailable (${res.status})`);
  _cache = await res.json();
  return _cache;
}

/**
 * Look up a patient + active order by free-text query
 * (patient name substring or exact admission number).
 * Returns { patient, order } | 'not-found'
 * Throws on connectivity problems (dashboard shows the error state).
 */
async function getPatientOrder(query) {
  const q = query.toLowerCase().trim();

  // Reserved demo queries to showcase the error state
  if (q === 'error' || q === 'a0000') {
    throw new Error('Simulated connection error');
  }

  const data = await loadDataset();
  const patient = data.patients.find(
    (p) => p.name.toLowerCase().includes(q) || p.admissionNumber.toLowerCase() === q
  );
  if (!patient) return 'not-found';

  const order = data.orders.find((o) => o.patientId === patient.id);
  if (!order) return 'not-found';

  return { patient, order };
}

window.DACSData = { getPatientOrder };
