export type DataOrigin = 'LIVE DATA' | 'MOCK DATA' | 'MIXED DATA';
export type ProgressMeasure = 'dose-quantity' | 'order-count';
export type Status = 'ToBeTreated'|'BeingPrepareForSpp'|'ReadyForSpp'|'SentToSpp'|'NotTreated'|'ReadyForRobot'|'OnHold'|'SentToRobot'|'Error'|'Cancelled'|'CancelledByExternalSource'|'CancelledByAdt'|'ReceivedTooLate'|'NeverPlanned';
export interface DispenseOrder { id:string; serviceId:string; serviceName:string; patientCode:string|null; quantity:number; administrationTargetTime:Date|null; sendingCycle:Date|null; rcp:number|null; status:Status; hasBeenProduct:boolean; hasStock:boolean; verified:boolean; warning:boolean; cancelledAfterDacsProduction:boolean; }
export interface WardProductionMetrics { wardId:string; wardName:string; patientCount:number; totalOrders:number; producedOrders:number; totalDoses:number; producedDoses:number; progressPercent:number|null; medianRcp:number|null; rcpCoveragePercent:number; cutoff:Date|null; estimatedDurationMinutes:number|null; exceptionCount:number; blocked:boolean; rationaleCodes:string[]; }
export interface CockpitInput { orders:DispenseOrder[]; productionStart:Date|null; origin:DataOrigin; partial:boolean; siteName:string; }
export interface CockpitView { wards:WardProductionMetrics[]; recommendation:WardProductionMetrics|null; totalDoses:number; producedDoses:number; patients:number; globalCutoff:Date|null; productionStart:Date|null; origin:DataOrigin; partial:boolean; lastUpdated:Date; exceptions:ExceptionItem[]; }
export interface ExceptionItem { code:string; count:number; severity:'info'|'warning'|'danger'; blocking:boolean; origin:DataOrigin; }
export interface ProductionRulesConfig { progressMeasure:ProgressMeasure; priorityStrategy:'rcp-then-progress'|'powerbi-formula'; slaWatchThresholdMinutes:number; completedProgressThresholdPercent:number; terminalStatuses:Status[]; }
export const DEFAULT_RULES: ProductionRulesConfig = {progressMeasure:'dose-quantity',priorityStrategy:'rcp-then-progress',slaWatchThresholdMinutes:30,completedProgressThresholdPercent:100,terminalStatuses:['Cancelled','CancelledByExternalSource','CancelledByAdt','ReceivedTooLate','NeverPlanned']};
